#!/usr/bin/env python3
"""Generate ``config/params.yaml`` (ROS 2 parameter file) from the ``Params`` dataclass.

``core/config.py`` is the single source of truth for parameter names, types and
defaults.  This tool writes them in the ``<node>: ros__parameters:`` layout and
keeps the comments of config.py: ``# ---- <group>`` rulers become group
headers, own-line comments stay above their field, inline comments stay inline.

Values are written so that both parsers agree on the type: floats always carry
a decimal point (PyYAML reads ``1e-05`` as a string, yaml-cpp as a float), bools
are ``true``/``false``, strings are single-quoted.  After writing, the file is
read back with PyYAML and ``Params.from_yaml`` and compared with ``Params()``
field by field (value and type); any mismatch is an error.

    python3 tools/gen_params_yaml.py            # (re)write config/params.yaml
    python3 tools/gen_params_yaml.py --check    # exit 1 if the file is out of date
"""
import argparse
import ast
import io
import math
import os
import re
import sys
import tokenize
from dataclasses import fields

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PKG_DIR = os.path.join(ROOT, 'src', 'tram_backup_odometry')
CONFIG_PY = os.path.join(PKG_DIR, 'tram_backup_odometry', 'core', 'config.py')
DEFAULT_OUT = os.path.join(PKG_DIR, 'config', 'params.yaml')
NODE_NAME = 'backup_odometry'
RULER = re.compile(r'^-{4,}\s*(.*?)\s*-*$')
ROS_NAME = re.compile(r'^[A-Za-z][A-Za-z0-9_]*$')
COMMENT_COL = 40

sys.path.insert(0, PKG_DIR)
from tram_backup_odometry.core.config import Params  # noqa: E402


def parse_layout(path):
    """Ordered items of the Params class body: ('group', title) | ('comment', text) |
    ('blank',) | ('field', name, inline_comment)."""
    src = open(path, encoding='utf-8').read()
    tree = ast.parse(src)
    cls = next(n for n in tree.body if isinstance(n, ast.ClassDef) and n.name == 'Params')
    field_span = {}
    first, last = None, cls.end_lineno
    for node in cls.body:
        if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            field_span[node.lineno] = (node.target.id, node.end_lineno)
            first = node.lineno if first is None else first
        elif isinstance(node, (ast.FunctionDef, ast.ClassDef)):
            last = min(last, node.lineno - 1)
            break
    comments = {}
    for tok in tokenize.generate_tokens(io.StringIO(src).readline):
        if tok.type == tokenize.COMMENT:
            own_line = not tok.line[:tok.start[1]].strip()
            comments[tok.start[0]] = (tok.string[1:].strip(), own_line)
    lines = src.splitlines()
    # own-line comments directly above the first field belong to it
    start = first
    while start - 1 > cls.lineno and (start - 1) in comments and comments[start - 1][1]:
        start -= 1

    items, ln = [], start
    while ln <= last:
        if ln in field_span:
            name, end = field_span[ln]
            inline = next((comments[k][0] for k in range(ln, end + 1)
                           if k in comments and not comments[k][1]), '')
            items.append(('field', name, inline))
            ln = end + 1
            continue
        if ln in comments and comments[ln][1]:
            text = comments[ln][0]
            m = RULER.match(text)
            items.append(('group', m.group(1)) if m else ('comment', text))
        elif not lines[ln - 1].strip():
            items.append(('blank',))
        ln += 1
    return items


def fmt_value(v):
    if isinstance(v, bool):
        return 'true' if v else 'false'
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        if math.isnan(v):
            return '.nan'
        if math.isinf(v):
            return '.inf' if v > 0 else '-.inf'
        s = repr(v)
        mant, _, exp = s.partition('e')
        if '.' not in mant:
            mant += '.0'
        return mant + ('e' + exp if exp else '')
    if isinstance(v, str):
        return "'" + v.replace("'", "''") + "'"
    raise TypeError('unsupported parameter type %r' % type(v))


def render(items, defaults):
    names = [f.name for f in fields(Params)]
    bad = [n for n in names if not ROS_NAME.match(n)]
    if bad:
        raise ValueError('not valid ROS parameter names: %s' % bad)
    out = [
        '# ROS 2 parameters of the %s node (tram_backup_odometry).' % NODE_NAME,
        '# GENERATED by tools/gen_params_yaml.py from tram_backup_odometry/core/config.py (Params).',
        '# Do not edit by hand: change the defaults in config.py and re-run',
        '#     python3 tools/gen_params_yaml.py',
        '# Units are SI unless the name says otherwise.  Node-only parameter (not listed here):',
        '#     maps_dir  (default <share>/tram_backup_odometry/maps)',
        '%s:' % NODE_NAME,
        '  ros__parameters:',
    ]
    ind = '    '
    seen = set()
    for it in items:
        if it[0] == 'group':
            out += ['', ind + '# ---- ' + it[1]]
        elif it[0] == 'comment':
            out.append(ind + '# ' + it[1] if it[1] else ind + '#')
        elif it[0] == 'field':
            name = it[1]
            if name not in names:
                continue
            seen.add(name)
            line = '%s%s: %s' % (ind, name, fmt_value(getattr(defaults, name)))
            if it[2]:
                line = line.ljust(COMMENT_COL) + '  # ' + it[2]
            out.append(line)
    missing = [n for n in names if n not in seen]
    if missing:  # fields the source parser did not see (should not happen)
        out += ['', ind + '# ---- other']
        out += ['%s%s: %s' % (ind, n, fmt_value(getattr(defaults, n))) for n in missing]
    return '\n'.join(out) + '\n'


def verify(text, path_for_from_yaml=None):
    """Read the text back and compare with Params() (value and type); returns error list."""
    defaults = Params()
    d = yaml.safe_load(text)[NODE_NAME]['ros__parameters']
    errs = []
    for f in fields(Params):
        want = getattr(defaults, f.name)
        if f.name not in d:
            errs.append('%s missing' % f.name)
            continue
        got = d[f.name]
        same_type = type(got) is type(want)
        same_val = got == want or (isinstance(want, float) and math.isnan(want) and math.isnan(got))
        if not (same_type and same_val):
            errs.append('%s: yaml %r (%s) != default %r (%s)'
                        % (f.name, got, type(got).__name__, want, type(want).__name__))
    extra = sorted(set(d) - {f.name for f in fields(Params)})
    errs += ['unknown key %s' % k for k in extra]
    if path_for_from_yaml:
        if Params.from_yaml(path_for_from_yaml) != defaults:
            errs.append('Params.from_yaml(%s) != Params()' % path_for_from_yaml)
    return errs


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--out', default=DEFAULT_OUT)
    ap.add_argument('--check', action='store_true', help='only check that --out is up to date')
    a = ap.parse_args(argv)

    text = render(parse_layout(CONFIG_PY), Params())
    errs = verify(text)
    if errs:
        print('generated YAML does not round-trip:\n  ' + '\n  '.join(errs), file=sys.stderr)
        return 1
    if a.check:
        cur = open(a.out, encoding='utf-8').read() if os.path.exists(a.out) else ''
        if cur != text:
            print('%s is out of date; run tools/gen_params_yaml.py' % a.out, file=sys.stderr)
            return 1
        print('%s is up to date (%d parameters)' % (a.out, len(fields(Params))))
        return 0
    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    with open(a.out, 'w', encoding='utf-8') as f:
        f.write(text)
    errs = verify(text, a.out)
    if errs:
        print('\n'.join(errs), file=sys.stderr)
        return 1
    print('wrote %s (%d parameters, round-trip OK)' % (a.out, len(fields(Params))))
    return 0


if __name__ == '__main__':
    sys.exit(main())
